=== pathos883/Software-Engineering-Group-11/Group11/src/main/resources/schedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by SSS (.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            Schema for personnel scheduling problems.
        </xs:documentation>
    </xs:annotation>
    <xs:element name="SchedulingPeriod">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="StartDate" type="xs:date"/>
                <xs:element name="EndDate" type="xs:date"/>
                <xs:element name="ShiftTypes" type="ShiftTypes"/>
                <xs:element name="Employees" type="Employees"/>
                <xs:element name="DayOffRequests" type="DayOffRequests" minOccurs="0"/>
                <xs:element name="DayOnRequests" type="DayOnRequests" minOccurs="0"/>
                <xs:element name="ShiftOffRequests" type="ShiftOffRequests" minOccurs="0"/>
                <xs:element name="ShiftOnRequests" type="ShiftOnRequests" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="ID" type="xs:string" use="required"/>
            <xs:attribute name="OrganisationID" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="ShiftTypes">
        <xs:sequence>
            <xs:element name="Shift" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="StartTime" type="xs:time"/>
                        <xs:element name="EndTime" type="xs:time"/>
                        <xs:element name="Description" type="xs:string" minOccurs="0"/>
                    </xs:all>
                    <xs:attribute name="ID" type="ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Employees">
        <xs:sequence>
            <xs:element name="Employee" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="ContractID" type="ID"/>
                        <xs:element name="Name" type="xs:string" minOccurs="0"/>
                        <xs:element name="HoursRemaining" type="xs:string"/>
                    </xs:all>
                    <xs:attribute name="ID" type="ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ConstraintAttributes">
        <xs:attribute name="on" type="xs:boolean" use="optional"/>
        <xs:attribute name="weight" type="xs:nonNegativeInteger" use="optional"/>
    </xs:complexType>
    <xs:complexType name="OnAndWeight">
        <xs:simpleContent>
            <xs:extension base="xs:nonNegativeInteger">
                <xs:attribute name="on" type="xs:boolean" use="optional"/>
                <xs:attribute name="weight" type="xs:nonNegativeInteger" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="WeightOnly">
        <xs:simpleContent>
            <xs:extension base="xs:boolean">
                <xs:attribute name="weight" type="xs:nonNegativeInteger" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="DayOffRequests">
        <xs:sequence>
            <xs:element name="DayOff" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="EmployeeID" type="ID"/>
                        <xs:element name="Date" type="xs:date"/>
                    </xs:sequence>
                    <xs:attribute name="weight" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DayOnRequests">
        <xs:sequence>
            <xs:element name="DayOn" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="EmployeeID" type="ID"/>
                        <xs:element name="Date" type="xs:date"/>
                    </xs:sequence>
                    <xs:attribute name="weight" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ShiftOffRequests">
        <xs:sequence>
            <xs:element name="ShiftOff" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ShiftTypeID" type="ID"/>
                        <xs:element name="EmployeeID" type="ID"/>
                        <xs:element name="Date" type="xs:date"/>
                    </xs:sequence>
                    <xs:attribute name="weight" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ShiftOnRequests">
        <xs:sequence>
            <xs:element name="ShiftOn" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:choice>
                            <xs:element name="ShiftTypeID" type="ID"/>
                        </xs:choice>
                        <xs:element name="EmployeeID" type="ID"/>
                        <xs:element name="Date" type="xs:date"/>
                    </xs:sequence>
                    <xs:attribute name="weight" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="WeekDay">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Sunday"/>
            <xs:enumeration value="Monday"/>
            <xs:enumeration value="Tuesday"/>
            <xs:enumeration value="Wednesday"/>
            <xs:enumeration value="Thursday"/>
            <xs:enumeration value="Friday"/>
            <xs:enumeration value="Saturday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="WeekDayOrAny">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="Weekend">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SaturdaySunday"/>
            <xs:enumeration value="FridaySaturdaySunday"/>
            <xs:enumeration value="FridaySaturdaySundayMonday"/>
            <xs:enumeration value="SaturdaySundayMonday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ID">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Z0-9._])+"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== pathos883/Software-Engineering-Group-11/Group11/src/main/resources/sample.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<SchedulingPeriod ID="sprint01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schedule.xsd">
    <StartDate>2010-01-01</StartDate>
    <EndDate>2010-01-28</EndDate>
    <ShiftTypes>
        <Shift ID="E">
            <StartTime>06:30:00</StartTime>
            <EndTime>14:30:00</EndTime>
            <Description>Early</Description>
        </Shift>
        <Shift ID="L">
            <StartTime>14:30:00</StartTime>
            <EndTime>22:30:00</EndTime>
            <Description>Late</Description>
        </Shift>
        <Shift ID="D">
            <StartTime>08:30:00</StartTime>
            <EndTime>16:30:00</EndTime>
            <Description>Day shift</Description>
        </Shift>
        <Shift ID="N">
            <StartTime>22:30:00</StartTime>
            <EndTime>06:30:00</EndTime>
            <Description>Night</Description>
        </Shift>
    </ShiftTypes>
    <Employees>
        <Employee ID="0">
            <ContractID>0</ContractID>
            <Name>0</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
        <Employee ID="1">
            <ContractID>0</ContractID>
            <Name>1</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
        <Employee ID="2">
            <ContractID>0</ContractID>
            <Name>2</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
        <Employee ID="3">
            <ContractID>0</ContractID>
            <Name>3</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
        <Employee ID="4">
            <ContractID>1</ContractID>
            <Name>4</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
        <Employee ID="5">
            <ContractID>1</ContractID>
            <Name>5</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
        <Employee ID="6">
            <ContractID>2</ContractID>
            <Name>6</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
        <Employee ID="7">
            <ContractID>2</ContractID>
            <Name>7</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
        <Employee ID="8">
            <ContractID>3</ContractID>
            <Name>8</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
        <Employee ID="9">
            <ContractID>3</ContractID>
            <Name>9</Name>
            <HoursRemaining>200</HoursRemaining>
        </Employee>
    </Employees>
    <DayOffRequests>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-02</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-08</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-07</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-05</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-15</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-04</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-25</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-16</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-01</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>0</EmployeeID>
            <Date>2010-01-27</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-20</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-15</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-18</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-11</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-17</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-04</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-08</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-07</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-23</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>1</EmployeeID>
            <Date>2010-01-06</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-08</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-01</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-21</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-16</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-04</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-22</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-14</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-09</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-17</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>2</EmployeeID>
            <Date>2010-01-20</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-14</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-21</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-17</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-20</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-16</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-25</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-10</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-13</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-09</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>3</EmployeeID>
            <Date>2010-01-18</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-18</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-07</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-02</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-28</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-17</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-21</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-24</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-06</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-04</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>4</EmployeeID>
            <Date>2010-01-10</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-04</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-22</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-14</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-07</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-27</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-25</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-17</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-20</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-09</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>5</EmployeeID>
            <Date>2010-01-23</Date>
        </DayOff>
        <DayOff weight="1">
            <EmployeeID>6</EmployeeID>
